language: node_js
node_js:
- "stable"
before_script:
  - npm install -g wintersmith
script: "wintersmith build"
branches:
  only:
  - master
  - live
deploy:
  - provider: s3
    access_key_id: AKIAIO6QVTUWZYLTPRZQ
    secret_access_key:
      secure: VStv7LL4tZjwRDMaakLcmzI96+Xf3dZaWLFVQd00fqCqAWxgvQtfiXUqJqBMqWF6Z3fZT/uuldcA1CZUrzlsLl7dXM+YT+xT7hzL4MJOXm/i7CcAz4StKlqQy8hZwXcf6m39qcbxvtuHaFPgWgaC1R5V/dJ2ahhgbwglmj8GqZI=
    bucket: staging.psimer.net
    region: us-west-2
    skip_cleanup: true
    local_dir: build
    on:
      branch: master
  - provider: s3
    access_key_id: AKIAIO6QVTUWZYLTPRZQ
    secret_access_key:
      secure: VStv7LL4tZjwRDMaakLcmzI96+Xf3dZaWLFVQd00fqCqAWxgvQtfiXUqJqBMqWF6Z3fZT/uuldcA1CZUrzlsLl7dXM+YT+xT7hzL4MJOXm/i7CcAz4StKlqQy8hZwXcf6m39qcbxvtuHaFPgWgaC1R5V/dJ2ahhgbwglmj8GqZI=
    bucket: www.psimer.net
    region: us-west-2
    skip_cleanup: true
    local_dir: build
    on:
      branch: live
