# Site settings
title: Donley P'Simer's Blog
email: donleyp@gmail.com
description: >
  This is Donley P'Simer's blog. I plan to write articles and essays
  on topics of interest to me and mine with the hope that they will
  spread good ideas. The opinions and viewpoints expressed here are 
  my own and do not represent those of my employer or any other 
  organization to which I am affiliated.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.psimer.net" # the base hostname & protocol for your site
twitter_username: donleyp
github_username:  donleyp

# Build settings
markdown: kramdown
exclude: [ 's3_website*' ]
gems: [jekyll-mermaid]
mermaid:
  src: '/scripts/mermaid.full.js'
